#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend delaneyautomations.tech
    timeout client  30000
    bind 0:80
    default_backend delaneyautomations.tech_backend

backend delaneyautomations.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 341617-web-01 54.146.91.194:80 check
    server 341617-web-02 54.90.4.143:80 check
EOT

sudo service haproxy restart
